apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-itzelll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-itzelll
  template:
    metadata:
      labels:
        app: graphql-itzelll
    spec:
      containers:
      - image: okteto.dev/graphql-itzelll:latest
        name: itzelll
        #envFrom:
        #- configMapRef:
        #    name: itzelll-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: graphql-itzelll
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "graphql-itzelll"
    port: 8080
  selector:
    app: graphql-itzelll
